//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

pub mod prelude;

pub mod quebec_blocked_executions;
pub mod quebec_claimed_executions;
pub mod quebec_failed_executions;
pub mod quebec_jobs;
pub mod quebec_pauses;
pub mod quebec_processes;
pub mod quebec_ready_executions;
pub mod quebec_recurring_executions;
pub mod quebec_recurring_tasks;
pub mod quebec_scheduled_executions;
pub mod quebec_semaphores;
