//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

pub mod prelude;

pub mod solid_queue_blocked_executions;
pub mod solid_queue_claimed_executions;
pub mod solid_queue_failed_executions;
pub mod solid_queue_jobs;
pub mod solid_queue_pauses;
pub mod solid_queue_processes;
pub mod solid_queue_ready_executions;
pub mod solid_queue_recurring_executions;
pub mod solid_queue_recurring_tasks;
pub mod solid_queue_scheduled_executions;
pub mod solid_queue_semaphores;
