#![allow(unused)]

//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

pub use super::quebec_blocked_executions::Entity as QuebecBlockedExecutions;
pub use super::quebec_claimed_executions::Entity as QuebecClaimedExecutions;
pub use super::quebec_failed_executions::Entity as QuebecFailedExecutions;
pub use super::quebec_jobs::Entity as QuebecJobs;
pub use super::quebec_pauses::Entity as QuebecPauses;
pub use super::quebec_processes::Entity as QuebecProcesses;
pub use super::quebec_ready_executions::Entity as QuebecReadyExecutions;
pub use super::quebec_recurring_executions::Entity as QuebecRecurringExecutions;
pub use super::quebec_recurring_tasks::Entity as QuebecRecurringTasks;
pub use super::quebec_scheduled_executions::Entity as QuebecScheduledExecutions;
pub use super::quebec_semaphores::Entity as QuebecSemaphores;
