#![allow(unused)]

//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

pub use super::solid_queue_blocked_executions::Entity as SolidQueueBlockedExecutions;
pub use super::solid_queue_claimed_executions::Entity as SolidQueueClaimedExecutions;
pub use super::solid_queue_failed_executions::Entity as SolidQueueFailedExecutions;
pub use super::solid_queue_jobs::Entity as SolidQueueJobs;
pub use super::solid_queue_pauses::Entity as SolidQueuePauses;
pub use super::solid_queue_processes::Entity as SolidQueueProcesses;
pub use super::solid_queue_ready_executions::Entity as SolidQueueReadyExecutions;
pub use super::solid_queue_recurring_executions::Entity as SolidQueueRecurringExecutions;
pub use super::solid_queue_recurring_tasks::Entity as SolidQueueRecurringTasks;
pub use super::solid_queue_scheduled_executions::Entity as SolidQueueScheduledExecutions;
pub use super::solid_queue_semaphores::Entity as SolidQueueSemaphores;
