//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use crate::context::{AppContext, ConcurrencyConflict, TableConfig};
use crate::query_builder;
use sea_orm::entity::prelude::*;
use sea_orm::{DatabaseTransaction, DbErr};
use std::sync::Arc;
use tracing::{info, warn};

#[allow(async_fn_in_trait)]
pub trait Retryable {
    /// Retry a failed job, routing it back through the same concurrency
    /// checks `core::route_job` applies at enqueue time so the declared
    /// `concurrency_limit` is honoured even on manual retry. Falls back to a
    /// direct ready_executions insert when the job has no concurrency_key.
    async fn retry(
        &self,
        txn: &DatabaseTransaction,
        table_config: &TableConfig,
        ctx: &Arc<AppContext>,
    ) -> Result<(), DbErr>;

    /// Bulk retry — same concurrency routing per job as :func:`retry`.
    /// Optional filters: `class_name`, `queue_name`, `since`/`until`
    /// (failed_executions.created_at range), and `error_like` (SQL LIKE
    /// pattern against the stored error message).
    #[allow(clippy::too_many_arguments)]
    async fn retry_all(
        &self,
        txn: &DatabaseTransaction,
        table_config: &TableConfig,
        ctx: &Arc<AppContext>,
        class_name: Option<&str>,
        queue_name: Option<&str>,
        since: Option<chrono::NaiveDateTime>,
        until: Option<chrono::NaiveDateTime>,
        error_like: Option<&str>,
    ) -> Result<u64, DbErr>;
}

/// Promote a retried job back to the right execution table based on its
/// concurrency state. Mirrors Solid Queue's `FailedExecution#retry` which
/// calls `job.prepare_for_execution` → `dispatch` → `acquire_concurrency_lock`.
///
/// - No concurrency_key → straight into ready_executions
/// - Has key + acquire succeeds → ready_executions
/// - Has key + acquire fails → blocked_executions (Block) or finished
///   (Discard)
async fn route_retried_job(
    txn: &DatabaseTransaction,
    table_config: &TableConfig,
    ctx: &Arc<AppContext>,
    job: &super::quebec_jobs::Model,
) -> Result<(), DbErr> {
    let concurrency_key = job.concurrency_key.as_deref().unwrap_or("");
    if concurrency_key.is_empty() {
        query_builder::ready_executions::insert(
            txn,
            table_config,
            job.id,
            &job.queue_name,
            job.priority,
        )
        .await?;
        return Ok(());
    }

    // Look up the runnable for this job's class to get the concurrency
    // policy. Falls back to safe defaults (limit=1, Block, default duration)
    // if the runnable isn't registered in this process — same defensive
    // behaviour as the dispatcher's scheduled-due promotion path.
    let (limit, duration_opt, on_conflict) = {
        #[cfg(feature = "python")]
        {
            ctx.runnables
                .read()
                .ok()
                .and_then(|runnables| {
                    runnables.get(&job.class_name).map(|r| {
                        (
                            r.concurrency_limit.unwrap_or(1),
                            r.concurrency_duration
                                .map(|s| chrono::Duration::seconds(s as i64)),
                            r.concurrency_on_conflict,
                        )
                    })
                })
                .unwrap_or((1, None, ConcurrencyConflict::Block))
        }
        #[cfg(not(feature = "python"))]
        {
            (1, None, ConcurrencyConflict::Block)
        }
    };

    let acquired = crate::semaphore::acquire_semaphore(
        txn,
        table_config,
        concurrency_key.to_string(),
        limit,
        duration_opt,
    )
    .await?;

    if acquired {
        query_builder::ready_executions::insert(
            txn,
            table_config,
            job.id,
            &job.queue_name,
            job.priority,
        )
        .await?;
        return Ok(());
    }

    // Slot taken — route per on_conflict so the limit is actually enforced.
    let duration = duration_opt.unwrap_or_else(|| {
        chrono::Duration::from_std(ctx.default_concurrency_control_period)
            .unwrap_or_else(|_| chrono::Duration::seconds(60))
    });
    match on_conflict {
        ConcurrencyConflict::Discard => {
            warn!(
                job_id = job.id,
                concurrency_key,
                "Retried job `{}' discarded due to concurrency limit",
                job.class_name
            );
            query_builder::jobs::mark_finished(txn, table_config, job.id).await?;
        }
        ConcurrencyConflict::Block => {
            let now = chrono::Utc::now().naive_utc();
            info!(
                job_id = job.id,
                concurrency_key,
                "Retried job `{}' blocked due to concurrency limit",
                job.class_name
            );
            query_builder::blocked_executions::insert(
                txn,
                table_config,
                job.id,
                &job.queue_name,
                job.priority,
                concurrency_key,
                now + duration,
            )
            .await?;
        }
    }
    Ok(())
}

#[allow(async_fn_in_trait)]
pub trait Discardable {
    /// Discard a failed job by removing it from failed_executions and optionally marking the job as finished
    async fn discard(
        &self,
        txn: &DatabaseTransaction,
        table_config: &TableConfig,
    ) -> Result<(), DbErr>;

    /// Discard all failed jobs by removing them from failed_executions and marking the jobs as finished.
    /// Optional filters: `class_name`, `queue_name`, `since`/`until` (failed_executions.created_at
    /// range), and `error_like` (SQL LIKE pattern against the stored error message).
    #[allow(clippy::too_many_arguments)]
    async fn discard_all(
        &self,
        txn: &DatabaseTransaction,
        table_config: &TableConfig,
        class_name: Option<&str>,
        queue_name: Option<&str>,
        since: Option<chrono::NaiveDateTime>,
        until: Option<chrono::NaiveDateTime>,
        error_like: Option<&str>,
    ) -> Result<u64, DbErr>;
}

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "solid_queue_failed_executions")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique)]
    pub job_id: i64,
    #[sea_orm(column_type = "Text", nullable)]
    pub error: Option<String>,
    pub created_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::quebec_jobs::Entity",
        from = "Column::JobId",
        to = "super::quebec_jobs::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    SolidQueueJobs,
}

impl Related<super::quebec_jobs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SolidQueueJobs.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

// Implement Retryable for Model
impl Retryable for Model {
    async fn retry(
        &self,
        txn: &DatabaseTransaction,
        table_config: &TableConfig,
        ctx: &Arc<AppContext>,
    ) -> Result<(), DbErr> {
        let job = query_builder::jobs::find_by_id(txn, table_config, self.job_id)
            .await?
            .ok_or_else(|| DbErr::Custom(format!("Job with ID {} not found", self.job_id)))?;

        route_retried_job(txn, table_config, ctx, &job).await?;
        query_builder::failed_executions::delete_by_job_id(txn, table_config, self.job_id).await?;

        info!("Retried failed job {}", self.job_id);
        Ok(())
    }

    async fn retry_all(
        &self,
        txn: &DatabaseTransaction,
        table_config: &TableConfig,
        ctx: &Arc<AppContext>,
        class_name: Option<&str>,
        queue_name: Option<&str>,
        since: Option<chrono::NaiveDateTime>,
        until: Option<chrono::NaiveDateTime>,
        error_like: Option<&str>,
    ) -> Result<u64, DbErr> {
        Entity
            .retry_all(
                txn,
                table_config,
                ctx,
                class_name,
                queue_name,
                since,
                until,
                error_like,
            )
            .await
    }
}

// Implement Discardable for Model
impl Discardable for Model {
    async fn discard(
        &self,
        txn: &DatabaseTransaction,
        table_config: &TableConfig,
    ) -> Result<(), DbErr> {
        // 1. Find job record
        let job_result = query_builder::jobs::find_by_id(txn, table_config, self.job_id).await?;

        if job_result.is_some() {
            // 2. Update job status to completed
            query_builder::jobs::mark_finished(txn, table_config, self.job_id).await?;

            // 3. Delete failed execution record
            query_builder::failed_executions::delete_by_job_id(txn, table_config, self.job_id)
                .await?;

            info!("Discarded failed job {}", self.job_id);
            Ok(())
        } else {
            Err(DbErr::Custom(format!(
                "Job with ID {} not found",
                self.job_id
            )))
        }
    }

    async fn discard_all(
        &self,
        txn: &DatabaseTransaction,
        table_config: &TableConfig,
        class_name: Option<&str>,
        queue_name: Option<&str>,
        since: Option<chrono::NaiveDateTime>,
        until: Option<chrono::NaiveDateTime>,
        error_like: Option<&str>,
    ) -> Result<u64, DbErr> {
        // 1. Get all failed job records
        let failed_executions = query_builder::failed_executions::find_all(
            txn,
            table_config,
            class_name,
            queue_name,
            since,
            until,
            error_like,
        )
        .await?;

        if failed_executions.is_empty() {
            return Ok(0);
        }

        let job_ids: Vec<i64> = failed_executions
            .iter()
            .map(|execution| execution.job_id)
            .collect();

        // 2. Update all related jobs to completed status
        for job_id in &job_ids {
            query_builder::jobs::mark_finished(txn, table_config, *job_id).await?;
        }

        // 3. Delete all failed execution records
        let count =
            query_builder::failed_executions::delete_by_job_ids(txn, table_config, job_ids).await?;

        info!("Discarded all {} failed jobs", count);
        Ok(count)
    }
}

// Implement Retryable for Entity
impl Retryable for Entity {
    async fn retry(
        &self,
        _txn: &DatabaseTransaction,
        _table_config: &TableConfig,
        _ctx: &Arc<AppContext>,
    ) -> Result<(), DbErr> {
        // Since Entity doesn't have a specific job_id, this method needs a different implementation
        Err(DbErr::Custom(
            "Cannot retry a job from Entity, please use a Model instance instead".to_string(),
        ))
    }

    async fn retry_all(
        &self,
        txn: &DatabaseTransaction,
        table_config: &TableConfig,
        ctx: &Arc<AppContext>,
        class_name: Option<&str>,
        queue_name: Option<&str>,
        since: Option<chrono::NaiveDateTime>,
        until: Option<chrono::NaiveDateTime>,
        error_like: Option<&str>,
    ) -> Result<u64, DbErr> {
        let failed_executions = query_builder::failed_executions::find_all(
            txn,
            table_config,
            class_name,
            queue_name,
            since,
            until,
            error_like,
        )
        .await?;

        if failed_executions.is_empty() {
            return Ok(0);
        }

        let job_ids: Vec<i64> = failed_executions
            .iter()
            .map(|execution| execution.job_id)
            .collect();

        let jobs = query_builder::jobs::find_by_ids(txn, table_config, job_ids.clone()).await?;

        // Route each retried job through the concurrency check so the
        // declared limit is enforced even on bulk retry (matches Solid
        // Queue's `FailedExecution.retry_all` → `dispatch_jobs` →
        // `Job.dispatch_all` partition between with/without
        // concurrency-limit groups).
        for job in &jobs {
            route_retried_job(txn, table_config, ctx, job).await?;
        }

        let count =
            query_builder::failed_executions::delete_by_job_ids(txn, table_config, job_ids).await?;

        info!("Retried all {} failed jobs", jobs.len());
        Ok(count)
    }
}

// Implement Discardable for Entity
impl Discardable for Entity {
    async fn discard(
        &self,
        _txn: &DatabaseTransaction,
        _table_config: &TableConfig,
    ) -> Result<(), DbErr> {
        // Since Entity doesn't have a specific job_id, this method needs a different implementation
        Err(DbErr::Custom(
            "Cannot discard a job from Entity, please use a Model instance instead".to_string(),
        ))
    }

    async fn discard_all(
        &self,
        txn: &DatabaseTransaction,
        table_config: &TableConfig,
        class_name: Option<&str>,
        queue_name: Option<&str>,
        since: Option<chrono::NaiveDateTime>,
        until: Option<chrono::NaiveDateTime>,
        error_like: Option<&str>,
    ) -> Result<u64, DbErr> {
        // 1. Get all failed job records
        let failed_executions = query_builder::failed_executions::find_all(
            txn,
            table_config,
            class_name,
            queue_name,
            since,
            until,
            error_like,
        )
        .await?;

        if failed_executions.is_empty() {
            return Ok(0);
        }

        let job_ids: Vec<i64> = failed_executions
            .iter()
            .map(|execution| execution.job_id)
            .collect();

        // 2. Update all related jobs to completed status
        for job_id in &job_ids {
            query_builder::jobs::mark_finished(txn, table_config, *job_id).await?;
        }

        // 3. Delete all failed execution records
        let count =
            query_builder::failed_executions::delete_by_job_ids(txn, table_config, job_ids).await?;

        info!("Discarded all {} failed jobs", count);
        Ok(count)
    }
}
